ARDMK_DIR	= /usr/share/arduino
ARDUINO_DIR	= /usr/share/arduino
AVR_TOOLS_DIR 	= /usr


ARDMK_DIR 	= /usr/share/arduino
BOARD_TAG	= Arduino Mega 2560 or Mega ADK
ARDUINO_PORT	= /dev/ttyACM*
ARDUINO_LIBS	=
MONITOR_PORT 	= /dev/ttyUSB*

include /usr/share/arduino/Arduino.mk
