ARDMK_DIR	= /usr/share/arduino
ARDUINO_DIR	= /usr/share/arduino
AVR_TOOLS_DIR 	= /usr


ARDMK_DIR 	= /usr/share/arduino
BOARD_TAG	= mega2560
ARDUINO_PORT	= /dev/ttyACM0
ARDUINO_LIBS	=

include /usr/share/arduino/Arduino.mk
